src/test/java/rest/JsonRequestTest.java
I made the following changes:
When executing mvn install, mvn test, it did not execute the defined tests. 
Change styling names of the methods.
Add Mockito.verify.
=> Tweaks to existing tests

src/test/java/rest/JsonRequestTest.java, src/test/java/rest/TextRequestTest.java
=> Added unit test for HttpPut request in jsonrequesttest.java and added tests for textrequest.java

src/test/java/rest/JsonRequestTest.java, src/test/java/rest/TextRequestTest.java
All tests now pass successfully via "mvn test" command.
=> Tweaks existing tests. 

src/main/java/rest/JsonRequest.java, src/main/java/rest/TextRequest.java, src/main/java/zosjobs/input/CommonJobParms.java, src/main/java/zosjobs/input/SubmitJclParms.java, src/main/java/zosjobs/input/SubmitJobParms.java, src/main/java/zosjobs/input/SubmitParms.java
Signed-off-by: Frank Giordano <giofr01@yahoo.com>
=> Styling changes.

src/main/java/zostso/IssueResponse.java, src/main/java/zostso/IssueTso.java, src/main/java/zostso/StartStopResponse.java, src/main/java/zostso/StartStopResponses.java, src/main/java/zostso/input/StartTsoParams.java, src/main/java/zostso/zosmf/TsoMessage.java, src/main/java/zostso/zosmf/TsoMessages.java, src/main/java/zostso/zosmf/TsoPromptMessage.java, src/main/java/zostso/zosmf/TsoResponseMessage.java, src/main/java/zostso/zosmf/ZosmfMessages.java, src/main/java/zostso/zosmf/ZosmfTsoResponse.java
no functionality yet - just skeleton code..
=> #12 ZOSTSO start

src/main/java/rest/IZoweRequest.java, src/main/java/rest/JsonRequest.java, src/main/java/rest/TextRequest.java, src/main/java/utility/Util.java, src/main/java/zostso/IssueResponse.java, src/main/java/zostso/IssueTso.java, src/main/java/zostso/StartTso.java, src/main/java/zostso/TsoConstants.java, src/main/java/zostso/input/StartTsoParams.java, src/test/java/rest/JsonRequestTest.java
=> More Building blocks code for Tso console commands

src/main/java/IssueTsoCommandTest.java, src/main/java/rest/JsonRequest.java, src/main/java/zostso/IssueTso.java, src/main/java/zostso/StartStopResponses.java, src/main/java/zostso/StartTso.java
Signed-off-by: Frank Giordano <giofr01@yahoo.com>
=> #12 - continuing adding building blocks for tso command functionality..

src/main/java/IssueTsoCommandTest.java, src/main/java/rest/JsonRequest.java, src/main/java/rest/TextRequest.java, src/main/java/zostso/StartTso.java, src/main/java/zostso/zosmf/TsoMessage.java, src/main/java/zostso/zosmf/TsoMessages.java, src/main/java/zostso/zosmf/TsoPromptMessage.java, src/main/java/zostso/zosmf/ZosmfTsoResponse.java
1. Made improvements to JsonRequest and TextRequest
2. Added Json parsing code for tso ZosmfTsoResponse
3. Added needed getter and setter
4. Display a tso response from IssueTsoCommandTest
=> Parse First Stage TSO Response Results

src/main/java/GetJobsTest.java, src/main/java/IssueCommandTest.java, src/main/java/IssueTsoCommandTest.java, src/main/java/SubmitJobsTest.java, src/main/java/zostso/IssueTso.java, src/main/java/zostso/StartTso.java
Signed-off-by: fg892105 <francesco.giordano@broadcom.com>
=> minor tweaks

src/main/java/utility/UtilDataset.java
Signed-off-by: nikunj goyal <nikunjgoyal31@gmail.com>
=> added dataset util

src/main/java/rest/JsonRequest.java, src/main/java/rest/Response.java, src/main/java/utility/UtilTso.java, src/main/java/zosconsole/IssueCommand.java, src/main/java/zosjobs/SubmitJobs.java, src/main/java/zostso/SendTso.java, src/test/java/utility/UtilTsoTest.java
=> TSO Unit Tests for UtilTso and Response Optional and Exception Handling Improvements

src/main/java/zosfiles/List.java, src/main/java/zosfiles/ZosFilesConstants.java
Signed-off-by: Leonid Baranov <leonid.baranov@broadcom.com>
=> Fix for list dataset parameters

src/main/java/ListDatasetsTest.java, src/main/java/zosfiles/ZosDsnList.java, src/main/java/zosfiles/ZosList.java
Specified a better name and removed references to java.util.List in the code and changed it to be List only after the renaming of the custom List class to ZosDsnList
=> Renamed to ZosDsnList

src/main/java/GetJobsTest.java, src/main/java/IssueCommandTest.java, src/main/java/SubmitJobsTest.java, src/main/java/rest/IZoweRequest.java, src/main/java/rest/JsonRequest.java, src/main/java/rest/TextRequest.java, src/main/java/zosjobs/GetJobs.java, src/main/java/zosjobs/SubmitJobs.java, src/test/java/rest/JsonRequestTest.java, src/test/java/zosjobs/GetJobTest.java
see #37 This is a proposal. You will see how much easier it is to test the code.
=> #37 GetJobs refactor to make it more testable

src/main/java/rest/JsonRequest.java, src/main/java/rest/Response.java, src/main/java/utility/UtilTso.java, src/main/java/zosconsole/IssueCommand.java, src/main/java/zosfiles/ZosDsnList.java, src/main/java/zosjobs/GetJobs.java, src/main/java/zosjobs/SubmitJobs.java, src/main/java/zostso/SendTso.java
Refactor related to issues #31 #9 #12 #10 #6  
Improvements and refactoring resulting in new patterns.  
- Maintainability changes in ZosDsnList via more modular aspects less duplication.
- Implemented Response object in ZosDsnList, GetJobs, and SubmitJobs leading to http code checking and custom error reporting.  
- Tweaks in custom http error reporting in SendTso, IssueCommand SubmitJobs.
- Improvements made in JsonRequest. 
- Refactor httpGet method in JsonRequest to conform with new Response object handling. 
- Handle http code success range correctly, see isHttpError variable introduced. 
- Tweak Response object variable name to better reflect purpose.
=> Http Response handling improvements and refactoring resulting in new patterns.  

pom.xml, src/main/java/rest/JsonRequest.java, src/test/java/rest/HttpResponseInvalidJsonMock.java, src/test/java/rest/HttpResponseMock.java, src/test/java/rest/JsonRequestTest.java
Due two changes for #31 amended and added tests.
=> JsonRequest Unit Tests

src/test/java/rest/JsonRequestTest.java, src/test/java/rest/TextRequestTest.java
Fixes and removal of some unused mocks.
=> JsonRequest and TextRequest tests amendments and additions

src/main/java/zosjobs/GetJobs.java, src/test/java/zosjobs/GetJobTest.java
- This also includes a fix in method GetSpoolContentById - the edge case of spool id. 
- Refactored the way to handle exception handling test cases in GetJobsTest
=> Added GetSpoolContentById unit test cases

src/main/java/rest/JsonDeleteRequest.java, src/main/java/rest/JsonGetRequest.java, src/main/java/rest/JsonPostRequest.java, src/main/java/rest/JsonPutRequest.java, src/main/java/rest/StreamGetRequest.java, src/main/java/rest/TextGetRequest.java, src/main/java/rest/TextPutRequest.java, src/main/java/rest/ZoweRequest.java, src/main/java/zosfiles/ZosDsnDownload.java, src/main/java/zosfiles/ZosDsnList.java, src/main/java/zosjobs/SubmitJobs.java, src/test/java/rest/JsonRequestTest.java
Rest Request improvements:
1. in executeHttpRequest() return empty response with http status code instead of null so at least the caller has http code to investigate further
2. changed headers to additionheaders for better readability. 
3. moved parse code inside if statement in JsonPostRequest as it shouldn't be executed unless if statement is true.
4. specified correct logger class name in StreamGetRequest.
=> Rest Request Improvements

src/main/java/rest/ZoweRequestFactory.java, src/main/java/zosfiles/ZosDsn.java, src/main/java/zosfiles/ZosDsnDownload.java, src/main/java/zosfiles/samples/DeleteDatasetTest.java
Signed-off-by: Leonid Baranov <leonid.baranov@broadcom.com>
=> Delete datasets and members

src/main/java/rest/JsonDeleteRequest.java, src/main/java/rest/JsonGetRequest.java, src/main/java/rest/JsonPostRequest.java, src/main/java/rest/JsonPutRequest.java, src/main/java/rest/Response.java, src/main/java/rest/StreamGetRequest.java, src/main/java/rest/TextGetRequest.java, src/main/java/rest/TextPutRequest.java, src/main/java/rest/ZoweRequestFactory.java, src/main/java/utility/UtilDataset.java, src/main/java/utility/UtilJobs.java, src/main/java/utility/UtilRest.java, src/main/java/zosconsole/IssueCommand.java, src/main/java/zosfiles/ZosDsn.java, src/main/java/zosfiles/ZosDsnDownload.java, src/main/java/zosfiles/ZosDsnList.java, src/main/java/zosjobs/GetJobs.java, src/main/java/zosjobs/SubmitJobs.java, src/main/java/zostso/SendTso.java, src/main/java/zostso/StartTso.java, src/main/java/zostso/StopTso.java, src/test/java/rest/JsonRequestTest.java, src/test/java/rest/TextRequestTest.java
- return empty response on execute http failure
- removed duplication across http verb processing of entity response retrieval 
- response isEmpty() method added to determine fully emptyness
- check http errors refactor better ability to use cross static utility with custom messaging
- added UtilRest class
- coded more and better safe guard checks
- added missing break for get_stream
=> Streamline Rest Code And Safe Guards

src/main/java/zosjobs/GetJobs.java
=> Method Java Doc For GetJobs 

src/main/java/zosjobs/SubmitJobs.java, src/main/java/zosjobs/samples/SubmitJobsTest.java
=> Java method comments and removed static usage for SubmitJobs 

src/main/java/utility/UtilTso.java, src/main/java/zosconsole/ConsoleConstants.java, src/main/java/zostso/IssueTso.java, src/main/java/zostso/samples/IssueTsoCommandTest.java
=> Added Constructor to IssueTso and more JavaDoc

pom.xml, src/main/java/utility/Util.java, src/main/java/utility/UtilTso.java, src/main/java/zosconsole/IssueCommand.java, src/main/java/zosfiles/ZosDsn.java, src/main/java/zosfiles/ZosDsnList.java, src/main/java/zosjobs/GetJobs.java, src/main/java/zosjobs/SubmitJobs.java, src/test/java/utility/UtilTsoTest.java, src/test/java/zosjobs/GetJobsByJsonGetRequestTest.java
=> Raw Type Usage Warnings -  org.json.simple 

src/main/java/zosconsole/ConsoleConstants.java, src/main/java/zosfiles/ZosDsnList.java, src/main/java/zosfiles/samples/ListDatasetsTest.java, src/main/java/zostso/IssueTso.java, src/main/java/zostso/SendTso.java, src/main/java/zostso/StartTso.java
=> Converted ZosDsnList, SendTso, and StartTso To Non Static

README.md, src/main/java/zosjobs/GetJobs.java, src/main/java/zosjobs/MonitorJobs.java, src/main/java/zosjobs/SubmitJobs.java, src/main/java/zosjobs/input/MonitorJobWaitForParms.java, src/main/java/zosjobs/response/CheckJobStatus.java, src/main/java/zosjobs/samples/MonitorJobsTest.java, src/main/java/zosjobs/types/JobStatus.java, src/main/java/zosjobs/types/JobTypes.java
=> Added MonitorJob feature

README.md, src/main/java/zosfiles/ZosDsnCopy.java, src/main/java/zosfiles/input/CopyParams.java, src/main/java/zosfiles/input/CreateParams.java, src/main/java/zosfiles/samples/CopyDatasetTest.java
Signed-off-by: Leonid Baranov <nurkambay@gmail.com>
=> Implement copy dataset functionality

src/main/java/utility/Timer.java, src/main/java/utility/Util.java, src/main/java/zosjobs/MonitorJobs.java
Add a Utility timer class and method.  Helps to avoid using the thread blocking Thread.sleep() method.
=> Timer Feature

README.md, src/main/java/utility/UtilIO.java, src/main/java/zosfiles/ZosDsn.java, src/main/java/zosfiles/ZosDsnDownload.java, src/main/java/zosfiles/ZosDsnList.java, src/main/java/zosjobs/GetJobs.java, src/main/java/zosjobs/MonitorJobs.java, src/main/java/zosjobs/SubmitJobs.java, src/main/java/zostso/StartTso.java, src/main/java/zostso/StopTso.java, src/main/java/zostso/samples/IssueTsoCommandTest.java, src/test/java/rest/JsonRequestTest.java
I introduced some isEmpty on Optional before. This PR will standardize it across project. This is more elegant and readable than !isPresent() and Java 11 added the isEmpty() method as such. I also added some more edge case empty string checks and standardized on the "not specified" wording for empty string.
=> Use Java 11 isEmpty method

src/main/java/zosfiles/input/CopyParams.java, src/main/java/zosfiles/input/CreateParams.java, src/main/java/zosfiles/input/DownloadParams.java, src/main/java/zosfiles/input/ListParams.java, src/main/java/zosfiles/input/ZosFilesParams.java, src/main/java/zosfiles/response/Dataset.java, src/main/java/zosjobs/input/CancelJobParams.java, src/main/java/zosjobs/input/DeleteJobParams.java, src/main/java/zosjobs/input/GetJobParms.java, src/main/java/zosjobs/response/Job.java
Removed if statement and rely on ofNullable() method only as this handled the != null if check. So we were doing it twice. This is handy Java 8 way with ofNullable and cuts down on verbosity! Thanks Leonid for pointing that out.
=> Consistent Builder Pattern

README.md, src/main/java/zosjobs/CancelJobs.java, src/main/java/zosjobs/DeleteJobs.java, src/main/java/zosjobs/input/CancelJobParams.java, src/main/java/zosjobs/input/DeleteJobParams.java, src/main/java/zosjobs/samples/CancelJobsTest.java, src/main/java/zosjobs/samples/DeleteJobsTest.java
Signed-off-by: Leonid Baranov <nurkambay@gmail.com>
=> Add test files for cancel and delete jobs

src/main/java/zosfiles/samples/ListDatasetsTest.java
Signed-off-by: Leonid Baranov <nurkambay@gmail.com>
=> Update list dataset sample

README.md, src/main/java/zosjobs/CancelJobs.java, src/main/java/zosjobs/samples/CancelJobsTest.java, src/main/java/zosjobs/samples/DeleteJobsTest.java
=> Complete Canceljobs Functionality

src/main/java/zosfiles/ZosDsn.java, src/main/java/zostso/IssueResponse.java, src/main/java/zostso/SendTso.java, src/main/java/zostso/StartStopResponse.java, src/main/java/zostso/input/SendTsoParms.java, src/main/java/zostso/input/StartTsoParams.java, src/main/java/zostso/input/StopTsoParms.java, src/main/java/zostso/samples/IssueTsoCommandTest.java
- Fixed typo in SendTsoParms use servletKey
- Consistent body wording in ZosDsn
- Consistent account number wording in StartTsoParams
- JavaDoc coverage added covers all of zostso package now
=> Tweaks to Existing Code

src/main/java/zosconsole/IssueCommand.java, src/main/java/zosfiles/ZosDsn.java, src/main/java/zosfiles/ZosDsnCopy.java, src/main/java/zosjobs/CancelJobs.java, src/main/java/zosjobs/SubmitJobs.java, src/test/java/utility/UtilTsoTest.java, src/test/java/zosjobs/GetJobsByJsonGetRequestTest.java
Sprinkle some Java 11 "var" love to the Json Request formulating code. Changed wording also. Overall looks less verbose and improves readability.
=> Json RequestBody Creation Consistency

src/main/java/zosjobs/samples/CancelJobsTest.java, src/main/java/zosjobs/samples/GetJobsTest.java, src/main/java/zosjobs/samples/MonitorJobsTest.java, src/main/java/zosjobs/samples/SubmitJobsTest.java
=> javadoc for zosjobs samples

src/main/java/zosjobs/DeleteJobs.java
Signed-off-by: nikunj goyal <nikunjgoyal31@gmail.com>
=> fixing delete jobs functionality

src/main/java/utility/UtilJobs.java, src/main/java/zosconsole/ConsoleResponse.java, src/main/java/zosconsole/samples/IssueCommandTest.java, src/main/java/zosjobs/samples/CancelJobsTest.java, src/main/java/zosjobs/samples/DeleteJobsTest.java, src/main/java/zosjobs/samples/GetJobsTest.java, src/main/java/zosjobs/samples/MonitorJobsTest.java, src/main/java/zosjobs/samples/SubmitJobsTest.java, src/main/java/zostso/samples/IssueTsoCommandTest.java
Completed javadoc for all of zosconsole package. 
Tweaks all samples with Z/OSMF references for better readability.
=> Javadoc Additional.

src/main/java/zosfiles/ZosDsnCopy.java, src/main/java/zosfiles/input/CopyParams.java, src/main/java/zosfiles/samples/CopyDatasetTest.java
- Added Response to help end user determine status of the copying
- Added more exception handling in copy method
- Improved sample example by adding response logging and covering all copy methods
- Default CopyParams replace value to true
related to #56
=> Enhance CopyDataset

src/main/java/zosfiles/ZosDsnCopy.java
=> return empty response if nothing is returned or exception seen

src/main/java/rest/Response.java, src/main/java/zosconsole/IssueCommand.java, src/main/java/zosfiles/input/CopyParams.java, src/main/java/zosfiles/input/CreateParams.java, src/main/java/zosfiles/input/DownloadParams.java, src/main/java/zosfiles/input/ListParams.java, src/main/java/zosfiles/input/ZosFilesParams.java, src/main/java/zosfiles/response/Dataset.java, src/main/java/zosjobs/CancelJobs.java, src/main/java/zosjobs/DeleteJobs.java, src/main/java/zosjobs/GetJobs.java, src/main/java/zosjobs/JobsConstants.java, src/main/java/zosjobs/MonitorJobs.java, src/main/java/zosjobs/input/CancelJobParams.java, src/main/java/zosjobs/input/CommonJobParms.java, src/main/java/zosjobs/input/DeleteJobParams.java, src/main/java/zosjobs/input/GetJobParms.java, src/main/java/zosjobs/input/JobFile.java, src/main/java/zosjobs/input/MonitorJobWaitForParms.java, src/main/java/zosjobs/response/Job.java, src/main/java/zosjobs/samples/CancelJobsTest.java, src/main/java/zosjobs/samples/DeleteJobsTest.java, src/main/java/zosjobs/samples/GetJobsTest.java
=> Conformity of our Builders and Rework of version handling in Delete and Cancel Jobs.

src/main/java/core/ZOSConnection.java, src/main/java/rest/Response.java, src/main/java/rest/ZoweRequest.java, src/main/java/utility/Timer.java, src/main/java/utility/Util.java, src/main/java/utility/UtilTso.java, src/main/java/zosjobs/MonitorJobs.java, src/main/java/zosjobs/input/GetJobParams.java, src/main/java/zosjobs/input/ModifyJobParams.java, src/main/java/zosjobs/input/MonitorJobWaitForParams.java, src/main/java/zosjobs/response/CheckJobStatus.java, src/main/java/zostso/CollectedResponses.java, src/main/java/zostso/SendResponse.java, src/main/java/zostso/StartStopResponses.java, src/main/java/zostso/input/SendTsoParams.java, src/main/java/zostso/input/StopTsoParams.java
- Utilized "final" in places I haven't catch previously.
- Change some truly expressions in a more sufficient manner.
=> Optimizations

src/main/java/utility/UtilJobs.java, src/main/java/zosjobs/examples/SubmitJobs.java, src/test/java/zosjobs/GetJobsByJsonGetRequestTest.java
Modify retCode to retcode to match the z/OSMF JSON reponse.
Add a sample for getRetCode() in SubmitJobs.
=> Fixes #115

src/main/java/rest/JsonGetRequest.java, src/main/java/utility/UtilRest.java, src/main/java/zosfiles/ZosDsnList.java, src/main/java/zosfiles/examples/ListDatasets.java
Modified try/catch block so exception isn't squashed.  Remove double-wrapped Optional from Response.
listDsn still isn't always behaving as I expect, but this should be addressed with Dataset validation.
Tested locally with: 
` @Test
public void listMembersTest() throws Exception {
ListParams parms = new ListParams.Builder().build();
ZosDsnList zosDsnList = new ZosDsnList(connection);
List<String> members = zosDsnList.listMembers(Configuration.CAW0JCL_DSName, parms);
// Member does exist
assertTrue(members.contains("TOMDPLOY"));
// Member does exist with valid character
assertTrue(members.contains("$J2ZDPLY"));
assertTrue(members.contains("#MSHDPHA"));
assertTrue(members.contains("TOMCR8IN"));
// Member does not exist
assertFalse(members.contains("NOTEXIST"));
}
@Test
public void …
=> Fixes #142

src/main/java/zosjobs/input/MonitorJobWaitForParams.java, src/main/java/zostso/IssueResponse.java, src/main/java/zostso/SendResponse.java, src/main/java/zostso/StartStopResponse.java, src/main/java/zostso/zosmf/ZosmfTsoResponse.java
=> Passing a non-null argument to Optional

src/main/java/zostso/StartStopResponses.java
1. Remove some over usage of Optional.
2. Added Exception checks in constructor.
3. Added helpful inline comments.
=> Streamline StartStopResponses class

src/main/java/rest/ZoweRequest.java, src/main/java/utility/Util.java, src/main/java/utility/UtilDataset.java, src/main/java/utility/UtilIO.java, src/main/java/utility/UtilJobs.java, src/main/java/zosconsole/IssueCommand.java, src/main/java/zosfiles/ZosDsn.java, src/main/java/zosfiles/ZosDsnCopy.java, src/main/java/zosfiles/ZosDsnDownload.java, src/main/java/zosfiles/ZosDsnList.java, src/main/java/zosfiles/examples/CopyDataset.java, src/main/java/zosfiles/examples/DownloadDataset.java, src/main/java/zosfiles/input/DownloadParams.java, src/main/java/zosjobs/CancelJobs.java, src/main/java/zosjobs/DeleteJobs.java, src/main/java/zosjobs/GetJobs.java, src/main/java/zosjobs/MonitorJobs.java, src/main/java/zosjobs/SubmitJobs.java, src/main/java/zostso/IssueTso.java, src/main/java/zostso/SendTso.java, src/main/java/zostso/StartTso.java, src/main/java/zostso/StopTso.java, src/main/javadoc/jquery/external/jquery/jquery.js
=> Special Characters Checks

src/main/java/utility/UtilDataset.java, src/main/java/zosfiles/ZosDsnList.java
Modify message for Http error 500 for UtilDataset to indicate that some requests will be invalid.  
=> Fixes #163

src/main/java/rest/JsonDeleteRequest.java, src/main/java/rest/JsonGetRequest.java, src/main/java/rest/JsonPostRequest.java, src/main/java/rest/JsonPutRequest.java, src/main/java/rest/StreamGetRequest.java, src/main/java/rest/TextGetRequest.java, src/main/java/rest/TextPutRequest.java, src/main/java/utility/UtilRest.java, src/test/java/rest/JsonRequestTest.java, src/test/java/rest/TextRequestTest.java
=> Url Validator

src/main/java/utility/UtilConsole.java, src/main/java/zosconsole/IssueCommand.java
Signed-off-by: Frank Giordano <giofr01@yahoo.com>
=> Convert Lambda with Method Reference

src/main/java/zostso/CollectedResponses.java, src/main/java/zostso/SendResponse.java, src/main/java/zostso/zosmf/ZosmfTsoResponse.java
Signed-off-by: Frank Giordano <giofr01@yahoo.com>
=> Streamline null checks

src/main/java/examples/zosfiles/CopyDataset.java, src/main/java/utility/UtilDataset.java, src/main/java/zosfiles/ZosDsnCopy.java
Return exception for ZosDsnCopy.copy().  Update examples and Http message, slightly.
=> Fixes #194

src/main/java/zosfiles/ZosDsnCopy.java
The JSON string {"from-dataset":{"member":"<member-name>"....  needs to be the actual member name, not the URI encoded name.
=> Fixes #199

src/main/java/zosfiles/ZosDsnDownload.java
Modified Download URL to match zOSMF:
GET /zosmf/restfiles/ds/[-(<volser>)/]<data-set-name>[(<member-name>)]
=> Fixes #208

pom.xml, src/main/java/zowe/client/sdk/utility/UtilJobs.java, src/main/java/zowe/client/sdk/zosjobs/GetJobs.java, src/main/java/zowe/client/sdk/zosjobs/JobsConstants.java, src/main/java/zowe/client/sdk/zosjobs/input/CommonJobParams.java, src/main/java/zowe/client/sdk/zosjobs/response/JobStepData.java
PR related to implementing functionality for #213
=> Add Step Data Job Retrieval #213

src/main/java/zowe/client/sdk/zosjobs/SubmitJobs.java
=> Fixes #237

src/main/java/zowe/client/sdk/rest/JsonDeleteRequest.java, src/main/java/zowe/client/sdk/rest/JsonGetRequest.java, src/main/java/zowe/client/sdk/rest/JsonPostRequest.java, src/main/java/zowe/client/sdk/rest/JsonPutRequest.java, src/main/java/zowe/client/sdk/rest/StreamGetRequest.java, src/main/java/zowe/client/sdk/rest/TextGetRequest.java, src/main/java/zowe/client/sdk/rest/TextPutRequest.java, src/main/java/zowe/client/sdk/rest/ZoweRequest.java, src/main/java/zowe/client/sdk/rest/ZoweRequestFactory.java, src/main/java/zowe/client/sdk/utility/UtilRest.java, src/main/java/zowe/client/sdk/zosconsole/IssueCommand.java, src/main/java/zowe/client/sdk/zosfiles/ZosDsn.java, src/main/java/zowe/client/sdk/zosfiles/ZosDsnCopy.java, src/main/java/zowe/client/sdk/zosfiles/ZosDsnDownload.java, src/main/java/zowe/client/sdk/zosfiles/ZosDsnList.java, src/main/java/zowe/client/sdk/zosjobs/CancelJobs.java, src/main/java/zowe/client/sdk/zosjobs/DeleteJobs.java, src/main/java/zowe/client/sdk/zosjobs/GetJobs.java, src/main/java/zowe/client/sdk/zosjobs/SubmitJobs.java, src/main/java/zowe/client/sdk/zosmfinfo/CheckStatus.java, src/main/java/zowe/client/sdk/zosmfinfo/ListDefinedSystems.java, src/main/java/zowe/client/sdk/zostso/SendTso.java, src/main/java/zowe/client/sdk/zostso/StartTso.java, src/main/java/zowe/client/sdk/zostso/StopTso.java, src/test/java/zowe/client/sdk/rest/JsonRequestTest.java, src/test/java/zowe/client/sdk/rest/TextRequestTest.java, src/test/java/zowe/client/sdk/zosconsole/IssueCommandTest.java
Added IssueCommandTest showing the new mocking tests!
=> Refactor Zowe Request Processing for Mock Readiness

pom.xml, src/main/java/zowe/client/sdk/core/SSHConnection.java, src/main/java/zowe/client/sdk/zosuss/README.md, src/main/java/zowe/client/sdk/zosuss/Shell.java, src/main/java/zowe/client/sdk/zosuss/package-info.java
=> ZOSUSS package with USS command execution functionality #220

src/main/java/zowe/client/sdk/zosjobs/CancelJobs.java, src/main/java/zowe/client/sdk/zosjobs/DeleteJobs.java
=> Fixes #246

src/main/java/zowe/client/sdk/zosjobs/GetJobs.java, src/test/java/zowe/client/sdk/zosjobs/GetJobsByJsonGetRequestTest.java
=> Update getStatus to always return step-Data for #252

pom.xml, src/main/java/zowe/client/sdk/zosjobs/SubmitJobs.java, src/main/java/zowe/client/sdk/zosjobs/input/SubmitJclParams.java, src/main/java/zowe/client/sdk/zosjobs/input/SubmitJobParams.java
Signed-off-by: cd612833 <corinne.destefano@broadcom.com>
=> Modify jcl symbol substitution to use a Map instead

src/main/java/zowe/client/sdk/zosfiles/uss/methods/UssDelete.java
introduced recursive directory deletions
=> UssDelete header functionality

src/main/java/zowe/client/sdk/zosfiles/uss/input/GetParams.java, src/main/java/zowe/client/sdk/zosfiles/uss/methods/UssGet.java, src/main/java/zowe/client/sdk/zosfiles/uss/methods/UssWrite.java
PR for UssGet scaffolding, minor updates to UssWrite javadoc
=> UssGet Scaffolding

src/test/java/zowe/client/sdk/zosFiles/UssListTest.java
=> Tweak test method names UssListTest

src/main/java/zowe/client/sdk/teamconfig/README.md, src/main/java/zowe/client/sdk/teamconfig/TeamConfig.java, src/main/java/zowe/client/sdk/teamconfig/exception/TeamConfigException.java, src/main/java/zowe/client/sdk/teamconfig/exception/package-info.java, src/main/java/zowe/client/sdk/teamconfig/keytar/IKeyTar.java, src/main/java/zowe/client/sdk/teamconfig/keytar/KeyTarImpl.java, src/main/java/zowe/client/sdk/teamconfig/service/KeyTarService.java, src/main/java/zowe/client/sdk/teamconfig/service/TeamConfigService.java, src/main/java/zowe/client/sdk/zosconsole/README.md, src/main/java/zowe/client/sdk/zosfiles/dsn/README.md, src/main/java/zowe/client/sdk/zosfiles/uss/README.md, src/main/java/zowe/client/sdk/zosjobs/README.md, src/main/java/zowe/client/sdk/zoslogs/README.md, src/main/java/zowe/client/sdk/zosmfinfo/README.md, src/main/java/zowe/client/sdk/zostso/README.md
This PR improves the exception handling for TeamConfig package.
This PR continues the exception handling changes project wide to accomplish the removal of most generic exception usage.
Changes:
- Added custom TeamConfigException exception
- Implemented TeamConfigException exception handling
Changes will be included in release 2.2.0. 
FYI 2.2.0 will also contain changes that consists of the removal of redundant project dependencies and exclusion of SLFJ4 logging binding dependency. This will make the Jar file less cluttered and streamlined.  In addition, to allow the end user to determine logging bindings.
=> Exception handling improvement for TeamConfig

src/main/java/zowe/client/sdk/zosjobs/JobsConstants.java, src/main/java/zowe/client/sdk/zosjobs/input/CommonJobParams.java, src/main/java/zowe/client/sdk/zosjobs/input/ModifyJobParams.java, src/main/java/zowe/client/sdk/zosjobs/input/MonitorJobWaitForParams.java, src/main/java/zowe/client/sdk/zosjobs/input/SubmitJobParams.java, src/main/java/zowe/client/sdk/zosjobs/methods/JobCancel.java, src/main/java/zowe/client/sdk/zosjobs/methods/JobDelete.java, src/main/java/zowe/client/sdk/zosjobs/methods/JobGet.java, src/main/java/zowe/client/sdk/zosjobs/methods/JobMonitor.java, src/main/java/zowe/client/sdk/zosjobs/methods/JobSubmit.java, src/test/java/zowe/client/sdk/zosjobs/GetJobsByJsonGetRequestTest.java
Improvements to exception handling in zosjobs package.
This PR request mainly contain updates to remove redundant exception handling.
Tweaked job constants for exception messaging.
=> Improvements to exception handling in zosjobs package.

.mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
Created a Maven wrapper using below command
mvn -N wrapper:wrapper
=> Added maven wrapper

README.md, pom.xml, src/main/java/zowe/client/sdk/zosjobs/input/ModifyJobParams.java, src/main/java/zowe/client/sdk/zosjobs/methods/JobCancel.java, src/test/java/zowe/client/sdk/zosjobs/methods/JobCancelTest.java
=> Cancel job and purge output

src/main/java/zowe/client/sdk/zostso/method/IssueTso.java
Made fixes to the while loop when retrieving additional tso messages for command processing.
=> Alternative tso package updates
